version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: sampahadmin-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - sampahadmin

    web:
        image: nginx:alpine
        container_name: sampah-nginx
        restart: unless-stopped
        ports:
            - "59:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - sampahadmin
networks:
    sampahadmin:
        driver: bridge

volumes:
    dbdata:
        driver: local
